version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: salon_spa_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: salon_spa_db
      MYSQL_USER: salonuser
      MYSQL_PASSWORD: salonpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - salon_network

  redis:
    image: redis:7-alpine
    container_name: salon_spa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - salon_network
    command: redis-server --appendonly yes

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: salon_spa_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: salonuser
      PMA_PASSWORD: salonpass
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - salon_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  salon_network:
    driver: bridge
